name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      ALIAS_TEST_DB: memory
      NEXT_TELEMETRY_DISABLED: "1"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run unit and integration tests
        run: npm run test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run E2E tests
        run: npm run test:e2e
